### ISSUE TITLE
AttributeError: 'BiasParameter' object has no attribute 'bias_filler'

### ISSUE THREAD

**Issue by ssongss** [dpaiton/deep-style#1]
Sorry to bother you. When I run: generateNetwork.py ,the prototex file can't generate and there is the attributeerror: 'BiasParameter' object has no attribute 'bias_filler'. Can you help me to solve this problems?
Thank you very much.

**Comment by dpaiton** [comment]
Hey @ssongss, it's no problem at all. I just pushed a commit with a minor change. Please be certain that line 16 is set correctly to the install path. In order to use this model you will need to download and install my caffe branch that includes a data, gramian, and bias layer implementation. You can find that here: https://github.com/dpaiton/caffe/tree/gramian. You will want to point `caffe_path` on line 16 to the caffe/python/dataLayer location in your caffe installation directory.
